// projects.js
export const PROJECTS = [
  {
    id: 1,
    title: "Residencia Aura",
    category: "Residencial",
    location: "Madrid, España",
    image: "/images/models/project_edwin.png",
    glbUrl: "/models/project_edwin.glb",
  },
  {
    id: 2,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "/images/models/project_street_8.png",
    glbUrl: "/models/project_street_8.glb",
  },
  {
    id: 3,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "/images/models/project_pamplona.png",
    glbUrl: "/models/project_pamplona.glb",
  },
  {
    id: 4,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "/images/models/project_av_zero.png",
    glbUrl: "/models/project_av_zero.glb",
  },
  {
    id: 5,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "/images/models/project_cabin.png",
    glbUrl: "/models/project_cabin.glb",
  },
  {
    id: 6,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    glbUrl: "/models/project_tania.glb",
  },
  {
    id: 7,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    glbUrl: "/models/project_tania.glb",
  },
  {
    id: 8,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    glbUrl: "/models/project_tania.glb",
  },
  {
    id: 9,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    glbUrl: "/models/project_tania.glb",
  },
  {
    id: 10,
    title: "Torre Prisma",
    category: "Corporativo",
    location: "Ciudad de México",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    glbUrl: "/models/project_tania.glb",
  },
];